FROM python:3

ENV GECKODRIVER_VER v0.31.0

RUN set -x \
   && apt update \
   && apt upgrade -y \
   && apt install -y \
       firefox-esr

# Get Rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo install geckodriver

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./src /app
COPY ./docker/app /app/startup

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout app.log \ 
	&& ln -sf /dev/stderr app.log

RUN mv /root/.cargo/bin/geckodriver /usr/bin/ \
    && chmod a+x /usr/bin/geckodriver 

ENTRYPOINT ["python", "/app/app.py"]